In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-macosx_11_0_arm64.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 567.4 kB/s eta 0:00:0000:0100:01
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 256.2 kB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.5

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
print(pd.__version__)

3.0.5

In [ ]:
try:
    import pandas as pd
    print("Pandas is installed. Version:", pd.__version__)
    # raise PandasException("This is a custom exception for demonstration purposes.")
except ValueError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except ModuleNotFoundError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except ImportError:
    print("Pandas is not installed. Please install it using 'pip install pandas'.")
except Exception as e:
    print("An error occurred while importing pandas:", str(e))

Pandas is installed. Version: 3.0.5

In [4]:
class PandasException(Exception):
    """Custom exception for Pandas-related errors."""
    def __init__(self, message):
        super().__init__(message)
        self.message = "PandasException: " + message

In [ ]:
try:
    import pandas as pd
    print("Pandas is installed. Version:", pd.__version__)
except PandasException as e:
    print(e.message)

In [ ]:
with open("a.txt", "wb") as file:
    content = file.read(10)
    file.tell()
    file.seek(10)
    print(content)

In [6]:
pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
data_frame = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
data_frame

   A  B
0  1  4
1  2  5
2  3  6

In [14]:
data_frame.loc[1:2, 'A']

1    2
2    3
Name: A, dtype: int64

In [19]:
data_frame.iloc[1, 0]

np.int64(2)

In [69]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 
                   'Age': [4, 5, 6],
                    'Salary': [50000, 60000, None],
  'Department': [1, 2, 3],
  'Manager':[None, 'John', None],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

df_new = df[(df['Age'] > 4) & (df['Salary'] < 70000)]
df_new

  Name  Age   Salary  Department Manager       skills
1  Bob    5  60000.0           2    John  [Java, C++]

In [37]:
df.isna()

    Name    Age  Salary  Department  Manager  skills
0  False  False   False       False     True   False
1  False  False   False       False    False   False
2  False  False   False       False     True    True

In [42]:
df.fillna({'Manager': 'Unknown'}, inplace=True)

      Name  Age  Salary Department  Manager         skills
0    Alice    4   50000         HR  Unknown  [Python, SQL]
1      Bob    5   60000         IT     John    [Java, C++]
2  Charlie    6   70000    Finance  Unknown           None

In [44]:
df.fillna({'Salary': df['Salary'].mean()}, inplace=True)

      Name  Age   Salary Department Manager         skills
0    Alice    4  50000.0         HR     NaN  [Python, SQL]
1      Bob    5  60000.0         IT    John    [Java, C++]
2  Charlie    6  55000.0    Finance     NaN           None

In [51]:
df.dropna(subset=['Salary'], inplace=True)
df

    Name  Age   Salary Department Manager         skills
0  Alice    4  50000.0         HR     NaN  [Python, SQL]
1    Bob    5  60000.0         IT    John    [Java, C++]

In [52]:
df.dropna()

  Name  Age   Salary Department Manager       skills
1  Bob    5  60000.0         IT    John  [Java, C++]

In [ ]:
department_df = pd.DataFrame({"id": [1, 2, 3, 4],
                              "department_name": ["HR", "IT", "Finance", "Technical"]})

In [ ]:
df_merged = pd.merge(df, department_df, 
                     left_on='Department', 
                     right_on='id', how='outer')
df_merged

,Name,Age,Salary,Department,Manager,skills,id,department_name
0,Alice,4.0,50000.0,1.0,NaN,"[Python, SQL]",1,HR
1,Bob,5.0,60000.0,2.0,John,"[Java, C++]",2,IT
2,Charlie,6.0,NaN,3.0,NaN,None,3,Finance
3,NaN,NaN,NaN,NaN,NaN,NaN,4,Technical

In [65]:
df_additional = pd.DataFrame({'Name': ['ABC', 'PQR', 'XYZ'], 
                   'Age': [14, 15, 16],
                    'Salary': [None, 60000, 40000],
  'Department': [4, 2, 1],
  'Manager':['Alice', 'Bob', 'Charlie'],
   'skills': [['Python', 'SQL'], ['Java', 'C++'], None]})

In [67]:
df_new = pd.concat([df, df_additional], ignore_index=True)
df_new

      Name  Age   Salary  Department  Manager         skills
0    Alice    4  50000.0           1      NaN  [Python, SQL]
1      Bob    5  60000.0           2     John    [Java, C++]
2  Charlie    6      NaN           3      NaN           None
3      ABC   14      NaN           4    Alice  [Python, SQL]
4      PQR   15  60000.0           2      Bob    [Java, C++]
5      XYZ   16  40000.0           1  Charlie           None

In [88]:
df_weather = pd.DataFrame({'City': ['New York', 'Los Angeles', 'Chicago'],
                           'Temperature': [30, 25, 20],
                           'Humidity': [70, 60, 80], 'Date': ['2023-01-01', '2023-01-02', '2023-01-03']})
df_weather

          City  Temperature  Humidity        Date
0     New York           30        70  2023-01-01
1  Los Angeles           25        60  2023-01-02
2      Chicago           20        80  2023-01-03

In [87]:
df_weather.transpose()

                      0            1           2
City           New York  Los Angeles     Chicago
Temperature          30           25          20
Humidity             70           60          80
Date         2023-01-01   2023-01-02  2023-01-03

In [ ]:
new_row = {"City": "New York", "Temperature": 40, "Humidity": 60, "Date": "2024-01-01"}

new_row = {"City": "New York", "Temperature": 32, "Humidity": 60, "Date": "2024-01-02"}
df_weather.loc[len(df_weather)] = new_row
df_weather['year'] = pd.to_datetime(df_weather['Date']).dt.year
df_weather

          City  Temperature  Humidity        Date  year
0     New York           30        70  2023-01-01  2023
1  Los Angeles           25        60  2023-01-02  2023
2      Chicago           20        80  2023-01-03  2023
3     New York           40        60  2024-01-01  2024
4     New York           32        60  2024-01-02  2024

In [91]:

df_weather.pivot_table(index='City', columns='year', values='Temperature', aggfunc='mean')

year         2023  2024
City
Chicago      20.0   NaN
Los Angeles  25.0   NaN
New York     30.0  36.0

In [92]:
df_weather.melt(id_vars=['City', 'year'], value_vars=['Temperature', 'Humidity'], var_name='Measurement', value_name='Value')

          City  year  Measurement  Value
0     New York  2023  Temperature     30
1  Los Angeles  2023  Temperature     25
2      Chicago  2023  Temperature     20
3     New York  2024  Temperature     40
4     New York  2024  Temperature     32
5     New York  2023     Humidity     70
6  Los Angeles  2023     Humidity     60
7      Chicago  2023     Humidity     80
8     New York  2024     Humidity     60
9     New York  2024     Humidity     60

In [93]:
df_weather = pd.DataFrame({'City': ['New York', 'Los Angeles', 'Chicago'],
                           'Temperature': [30, 25, 20],
                           'Humidity': [70, 60, 80], 'Date': ['2023-01-01', '2023-01-02', '2023-01-03']})
df_weather

          City  Temperature  Humidity        Date
0     New York           30        70  2023-01-01
1  Los Angeles           25        60  2023-01-02
2      Chicago           20        80  2023-01-03

In [97]:

# Original DataFrame
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'], 
    'Age': [4, 5, 6],
    'Salary': [50000, 60000, None],
    'Department': [1, 2, 3],
    'Manager': [None, 'John', None],
    'skills': [['Python', 'SQL'], ['Java', 'C++'], None]
})

# New data repeating Department IDs 1, 2, and 1
new_data = pd.DataFrame({
    'Name': ['David', 'Emma', 'Frank'],
    'Age': [7, 8, 5],
    'Salary': [70000, 65000, 52000],
    'Department': [1, 2, 1],  # Repeated department IDs
    'Manager': ['Sarah', 'John', 'Sarah'],
    'skills': [['Go', 'Docker'], ['AWS', 'Python'], ['R']]
})

# Concatenate and reset index
df = pd.concat([df, new_data], ignore_index=True)
print(df)

      Name  Age   Salary  Department Manager         skills
0    Alice    4  50000.0           1     NaN  [Python, SQL]
1      Bob    5  60000.0           2    John    [Java, C++]
2  Charlie    6      NaN           3     NaN           None
3    David    7  70000.0           1   Sarah   [Go, Docker]
4     Emma    8  65000.0           2    John  [AWS, Python]
5    Frank    5  52000.0           1   Sarah            [R]

In [109]:
new_df = df.groupby('Department').apply(lambda x: x['Salary'].mean()).reset_index(name='Average_Salary')

In [ ]:
new_df.dropna()
new_df.fillna('Average_Salary', new_df['Average_Salary'].mean(), inplace=True)

   Department  Average_Salary
0           1    57333.333333
1           2    62500.000000

In [115]:
new_df.filter(items=['Average_Salary'])

   Average_Salary
0    57333.333333
1    62500.000000
2             NaN

In [ ]:
new_df.pipe(lambda x: x.sort_values(by='Average_Salary', ascending=False))

   Department  Average_Salary
1           2    62500.000000
0           1    57333.333333
2           3             NaN

In [116]:
%pip install numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.11/site-packages (2.4.6)

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np

In [134]:
new_array =np.array([2, 2], dtype=np.int64)
new_array

array([2, 2])

In [ ]:
arr = np.array((3, 3), dtype=np.int32)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [130]:
new_array.shape

(2, 2)

In [136]:
new_array.fill(0)
new_array

array([0, 0])

In [ ]:
a = np.array([1, 2, 3])
np.add.reduce(a)
np.add.accumulate(a)

array([1, 3, 6])

In [7]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7]], dtype=np.int32)
arr.strides

(16, 4)

In [8]:
new_arr = arr.T
new_arr.strides

(4, 16)

In [9]:
new_arr

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]], dtype=int32)

In [11]:
new_arr[1, 0] = 8

In [12]:
arr

array([[1, 8, 3, 4],
       [4, 5, 6, 7]], dtype=int32)

In [15]:
#reval vs flattern
new_ravel = arr.ravel()
new_ravel

array([1, 8, 3, 4, 4, 5, 6, 7], dtype=int32)

In [16]:
new_ravel[1] = 10
new_ravel

array([ 1, 10,  3,  4,  4,  5,  6,  7], dtype=int32)

In [17]:
arr

array([[ 1, 10,  3,  4],
       [ 4,  5,  6,  7]], dtype=int32)

In [18]:
new_flatten_arr = arr.flatten()
new_flatten_arr

array([ 1, 10,  3,  4,  4,  5,  6,  7], dtype=int32)

In [20]:
new_flatten_arr[1] = 12
new_flatten_arr

array([ 1, 12,  3,  4,  4,  5,  6,  7], dtype=int32)

In [21]:
arr

array([[ 1, 10,  3,  4],
       [ 4,  5,  6,  7]], dtype=int32)

In [31]:
arr1 = np.array([[1, 2], [3, 4]], dtype=np.int32, order='C')
arr1.strides

(8, 4)

In [32]:
arr2 = np.array([[1, 2], [3, 4]], dtype=np.int32, order='F')
arr2.strides

(4, 8)

In [33]:
arr1.ravel()

array([1, 2, 3, 4], dtype=int32)

In [37]:
arr2.ravel(order='F')

array([1, 3, 2, 4], dtype=int32)

In [3]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.split(arr, 3)

ValueError: array split does not result in an equal division

In [7]:
np.array_split(arr, 3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [8]:
#ufunc
arr = np.array([1, 2, 3, 4, 5])
np.add.reduce(arr)

np.int64(15)

In [11]:
np.add.accumulate(arr)

array([ 1,  3,  6, 10, 15])

In [12]:
arr1 = np.array([[1, 2], [3, 4]], dtype=np.int32)
arr2 = np.array([[5, 6], [7, 8]], dtype=np.int32)

In [13]:
np.add.outer(arr1, arr2)

array([[[[ 6,  7],
         [ 8,  9]],

        [[ 7,  8],
         [ 9, 10]]],


       [[[ 8,  9],
         [10, 11]],

        [[ 9, 10],
         [11, 12]]]], dtype=int32)

In [18]:
# substract
arr1 = np.array([[1, 2], [3, 4]], dtype=np.int32)
arr2 = np.array([[5, 6], [7, 8]], dtype=np.int32)
def add(a: np.int32, b: np.int32) -> np.int32:
    return a + b
# add - function name
# 2 - number of input arguments
# 1 - number of output arguments
my_add = np.frompyfunc(add, 2, 1 )
# my_add(arr1, arr2)
my_add(arr1, arr2)

array([[6, 8],
       [10, 12]], dtype=object)

In [21]:
#np.vectorize(add)(arr1, arr2)
from numba import vectorize, float32, float64
@vectorize([float64(float32, float32)], target="parallel" )
def add(x, y):
    return x + y
arr1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
arr2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
add(arr1, arr2)

array([[ 6.,  8.],
       [10., 12.]])

In [3]:
df = pd.DataFrame(
    {
        "sales": [200.0, 320.0, 150.0, 480.0, 220.0, 390.0, 180.0, 510.0],
        "ad_camp": [10.0, 25.0, 5.0, 40.0, 12.0, 30.0, 8.0, 45.0],
        "campaign": [
            "Email",
            "Social",
            "Email",
            "TV",
            "Email",
            "Social",
            "Email",
            "TV",
        ],
    }
)

In [31]:
data = {
    "order_id": [f"ORD-{i:04d}" for i in range(1, 9)],
    "amount": [120.0, 45.0, 310.0, 95.0, 500.0, 35.0, 210.0, 80.0],
    "gateway": [
        "Stripe",
        "Razorpay",
        "Stripe",
        "Razorpay",
        "Stripe",
        "Razorpay",
        "Stripe",
        "Razorpay",
    ],
    "method": ["Card", "UPI", "UPI", "Card", "Card", "UPI", "Card", "UPI"],
    "processing_fee": [3.48, 0.90, 8.99, 1.90, 14.50, 0.70, 6.09, 1.60],
    "is_failed": [0, 0, 1, 0, 1, 0, 0, 0],  # Binary failure flag
}

In [8]:
%pip install patsy

Collecting patsy
  Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 80.8 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.4 in ./.venv/lib/python3.11/site-packages (from patsy) (2.4.6)
Requirement already satisfied: packaging in ./.venv/lib/python3.11/site-packages (from patsy) (26.3)
Installing collected packages: patsy
Successfully installed patsy-1.0.3

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
import patsy

In [ ]:
y, X = patsy.dmatrices("sales ~ ad_camp + campaign", data=df, return_type="dataframe")
print(X.shape)
print(X)
print(X.design_info)

(8, 4)
   Intercept  campaign[T.Social]  campaign[T.TV]  ad_camp
0        1.0                 0.0             0.0     10.0
1        1.0                 1.0             0.0     25.0
2        1.0                 0.0             0.0      5.0
3        1.0                 0.0             1.0     40.0
4        1.0                 0.0             0.0     12.0
5        1.0                 1.0             0.0     30.0
6        1.0                 0.0             0.0      8.0
7        1.0                 0.0             1.0     45.0
DesignInfo(['Intercept', 'campaign[T.Social]', 'campaign[T.TV]', 'ad_camp'],
           factor_infos={EvalFactor('ad_camp'): FactorInfo(factor=EvalFactor('ad_camp'),
                                    type='numerical',
                                    state=<factor state>,
                                    num_columns=1),
                         EvalFactor('campaign'): FactorInfo(factor=EvalFactor('campaign'),
                                    type='categorical',
                                    state=<factor state>,
                                    categories=('Email', 'Social', 'TV'))},
           term_codings=OrderedDict([(Term([]),
                                      [SubtermInfo(factors=(),
                                                   contrast_matrices={},
                                                   num_columns=1)]),
                                     (Term([EvalFactor('campaign')]),
                                      [SubtermInfo(factors=(EvalFactor('campaign'),),
                                                   contrast_matrices={EvalFactor('campaign'): ContrastMatrix(array([[0., 0.],
                                                                                            [1., 0.],
                                                                                            [0., 1.]]),
                                                                                     ['[T.Social]',
                                                                                      '[T.TV]'])},
                                                   num_columns=2)]),
                                     (Term([EvalFactor('ad_camp')]),
                                      [SubtermInfo(factors=(EvalFactor('ad_camp'),),
                                                   contrast_matrices={},
                                                   num_columns=1)])]))

In [12]:
%pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.15.0-cp311-cp311-macosx_11_0_arm64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 4.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy<3,>=1.23.5 in ./.venv/lib/python3.11/site-packages (from statsmodels) (2.4.6)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl (20.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 10.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pandas!=2.1.0,>=1.4 in ./.venv/lib/python3.11/site-packages (from statsmodels) (3.0.5)
Requirement already satisfied: patsy>=0.5.6 in ./.venv/lib/python3.11/site-packages (from statsmodels) (1.0.3)
Requirement already satisfied: packaging>=21.3 in ./.venv/lib/python3.11/site-packages (from statsmodels) (26.3)
Collecting formulaic>=1.1.0 (from statsmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 15.1 MB/s eta 0:00:00
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Collecting narwhals>=1.17 (from formulaic>=1.1.0->statsmodels)
  Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.0/474.0 kB 11.8 MB/s eta 0:00:0000:01
Requirement already satisfied: typing-extensions>=4.2.0 in ./.venv/lib/python3.11/site-packages (from formulaic>=1.1.0->statsmodels) (4.16.0)
Collecting wrapt>=1.0 (from formulaic>=1.1.0->statsmodels)
  Downloading wrapt-2.5.0-cp311-cp311-macosx_11_0_arm64.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.5/105.5 kB 9.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Installing collected packages: wrapt, scipy, narwhals, interface-meta, formulaic, statsmodels
Successfully installed formulaic-1.2.2 interface-meta-2.0.1 narwhals-2.26.0 scipy-1.17.1 statsmodels-0.15.0 wrapt-2.5.0

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [13]:
from statsmodels.api import OLS
from statsmodels.formula.api import ols

In [20]:
ols_model = ols("sales ~ ad_camp + campaign", data=df).fit()
ols_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.997
Model:                            OLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                     458.6
Date:                Sat, 03 Oct 2026   Prob (F-statistic):           1.57e-05
Time:                        11:01:04   Log-Likelihood:                -27.000
No. Observations:                   8   AIC:                             62.00
Df Residuals:                       4   BIC:                             62.32
Df Model:                           3
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            100.0000     13.151      7.604      0.002      63.487     136.513
campaign[T.Social]   -20.0000     27.465     -0.728      0.507     -96.256      56.256
campaign[T.TV]       -30.0000     47.708     -0.629      0.564    -162.460     102.460
ad_camp               10.0000      1.390      7.194      0.002       6.140      13.860
==============================================================================
Omnibus:                        0.136   Durbin-Watson:                   1.750
Prob(Omnibus):                  0.934   Jarque-Bera (JB):                0.333
Skew:                           0.000   Prob(JB):                        0.846
Kurtosis:                       2.000   Cond. No.                         413.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp311-cp311-macosx_12_0_arm64.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 244.3 kB/s eta 0:00:0000:0100:02
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.1/306.1 kB 715.2 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: narwhals>=2.0.1 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (2.26.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: threadpoolctl, cloudpickle, joblib, scikit-learn
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 scikit-learn-1.9.1 threadpoolctl-3.7.0

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [21]:
x_train = patsy.dmatrix("ad_camp + campaign", data=df, return_type="dataframe")
y_train = df["sales"].to_numpy()

In [23]:
from sklearn.linear_model import LinearRegression

In [26]:
reg = LinearRegression(fit_intercept=False )
reg.fit(x_train, y_train)

LinearRegression(fit_intercept=False)

In [29]:
df_test = pd.DataFrame({
    "ad_camp": [15.0, 20.0, 30.0, 10.0],
    "campaign": ["Email", "Social", "TV", "Email"]
})

predictions = reg.predict(patsy.dmatrix("ad_camp + campaign", data=df_test, return_type="dataframe"))

In [30]:
for each in predictions:
    print(each)

249.99999999999866
279.99999999999835
369.99999999999744
199.9999999999991

In [42]:
data

{'order_id': ['ORD-0001',
  'ORD-0002',
  'ORD-0003',
  'ORD-0004',
  'ORD-0005',
  'ORD-0006',
  'ORD-0007',
  'ORD-0008'],
 'amount': [120.0, 45.0, 310.0, 95.0, 500.0, 35.0, 210.0, 80.0],
 'gateway': ['Stripe',
  'Razorpay',
  'Stripe',
  'Razorpay',
  'Stripe',
  'Razorpay',
  'Stripe',
  'Razorpay'],
 'method': ['Card', 'UPI', 'UPI', 'Card', 'Card', 'UPI', 'Card', 'UPI'],
 'processing_fee': [3.48, 0.9, 8.99, 1.9, 14.5, 0.7, 6.09, 1.6],
 'is_failed': [0, 0, 1, 0, 1, 0, 0, 0]}

In [44]:
df = pd.DataFrame(data)

y_train, x_train = patsy.dmatrices("is_failed ~ amount + gateway + method + processing_fee", data=df, return_type="dataframe")
x_train

   Intercept  gateway[T.Stripe]  method[T.UPI]  amount  processing_fee
0        1.0                1.0            0.0   120.0            3.48
1        1.0                0.0            1.0    45.0            0.90
2        1.0                1.0            1.0   310.0            8.99
3        1.0                0.0            0.0    95.0            1.90
4        1.0                1.0            0.0   500.0           14.50
5        1.0                0.0            1.0    35.0            0.70
6        1.0                1.0            0.0   210.0            6.09
7        1.0                0.0            1.0    80.0            1.60

In [36]:
reg = LinearRegression(fit_intercept=False)
reg.fit(x_train, y_train)

LinearRegression(fit_intercept=False)

In [38]:
test_data = {"amount": [100.0, 200.0, 300.0, 400.0],
              "gateway": ["Razorpay", "Stripe", "Razorpay", "Stripe"], "method": ["Card", "UPI", "Card", "UPI"], "processing_fee": [5.0, 10.0, 5.0, 10.0]}

In [39]:
predictions = reg.predict(patsy.dmatrix("amount + gateway + method + processing_fee", data=test_data, return_type="dataframe"))

In [40]:
for each in predictions:
    print(each)

[-0.82746837]
[-0.45747898]
[1.13759622]
[1.50758562]