In [ ]:
# before pandas - database - 
# data - row and column - structured data
# database - 2 table - related data - join - inner, outer, left, right
# pandas - data analysis - data manipulation - data cleaning - data visualization

In [1]:
# database -query - visualization - minimal
# get data from database
# sara data - database, files analysis.
# analysis - past data - predictive analysis - future data - prediction - machine learning - deep learning
# amazon - product highlight - kab highlight - kab discount. depends upon the 
# behviour of the user - highlight 
import pandas as pd
# data structured - row and column - data frame - 2D array - 2D table
# row - series - 1D array - 1D table
# row and colum - 2D array - data frame
# arr[0][1] - df.iloc[0, 1] - column - names - nahi
# pandas - can do that - column names - row and column - data frame - 2D array - 2D table
#

In [6]:
ser = pd.Series([1, "Prashant", 3.5, True, None])
type(ser)
print(ser[1])

Prashant

In [2]:
df = pd.DataFrame([[1, "Prashant", 3.5, True, None], [2, "Rohit", 4.5, False, None], [3, "Sita", 5.0, True, None]], columns=["ID", "Name", "Score", "Passed", "Remarks"])
print(df)

   ID      Name  Score  Passed Remarks
0   1  Prashant    3.5    True    None
1   2     Rohit    4.5   False    None
2   3      Sita    5.0    True    None

In [3]:
df.iloc[1, 2] # arr[0][1]

np.float64(4.5)

In [4]:
df.loc[1, "Score"] # arr[0][1] - column name - score

np.float64(4.5)

In [ ]:
df

In [5]:
df[["Score"]] # column name - score - series - 1D array - 1D table

   Score
0    3.5
1    4.5
2    5.0

In [6]:
df.head(2)

   ID      Name  Score  Passed Remarks
0   1  Prashant    3.5    True    None
1   2     Rohit    4.5   False    None

In [7]:
df.tail(2)

   ID   Name  Score  Passed Remarks
1   2  Rohit    4.5   False    None
2   3   Sita    5.0    True    None

In [21]:
new_df = df.dropna(inplace=False)
new_df # dropna - remove rows with NaN values - inplace - True - modify original df

Empty DataFrame
Columns: [ID, Name, Score, Passed, Remarks]
Index: []

In [ ]:
df.replace("No remarks", "Prashant") 

# replace - replace values in df - to_replace - value - inplace - True - modify original df

   ID      Name  Score  Passed Remarks
0   1  Prashant    3.5    True    None
1   2     Rohit    4.5   False    None
2   3      Sita    5.0    True    None

In [22]:
df.fillna("No Remarks", inplace=True)

   ID      Name  Score  Passed     Remarks
0   1  Prashant    3.5    True  No Remarks
1   2     Rohit    4.5   False  No Remarks
2   3      Sita    5.0    True  No Remarks

In [ ]:
df.fillna(df.mean("score"), inplace=True) # fillna - replace NaN values with mean of the column - inplace - True - modify original df

In [32]:
df.loc[len(df)] = [5, "Rahul", None, False, "No Remarks"] # append - add row to df - ignore_index - True - reset index

In [31]:
df.dropna(inplace=True) # dropna - remove rows with NaN values - inplace - True - modify original df

In [33]:
df

   ID      Name Score  Passed     Remarks
0   1  Prashant   3.5    True  No Remarks
1   2     Rohit   4.5   False  No Remarks
2   3      Sita   5.0    True  No Remarks
3   5     Rahul  None   False  No Remarks

In [41]:
df.fillna(df["Score"].mean(), inplace=True, axis=0) # fillna - replace NaN values with mean of the column - inplace - True - modify original df - axis - 0 - column wise, 1 - row wise

   ID      Name     Score  Passed     Remarks
0   1  Prashant       3.5    True  No Remarks
1   2     Rohit       4.5   False  No Remarks
2   3      Sita       5.0    True  No Remarks
3   5     Rahul  4.333333   False  No Remarks

In [ ]:
df.read_csv("data.csv") # read_csv - read csv file - path - file path - sep - separator - delimiter - header - column names - index_col - index column - usecols - columns to read - dtype - data type - na_values - missing values - parse_dates - date columns

In [42]:
df2 = pd.DataFrame([[1, "HR"], [2, "Finance"], [3, "IT"]], columns=["ID", "Department"])

In [ ]:

new_df # merge - join - inner, outer, left, right - on - column name - how - type of join

   ID      Name     Score  Passed     Remarks Department
0   1  Prashant       3.5    True  No Remarks         HR
1   2     Rohit       4.5   False  No Remarks    Finance
2   3      Sita       5.0    True  No Remarks         IT
3   5     Rahul  4.333333   False  No Remarks        NaN

In [46]:
df["Dept_ID"] = [1, 1, 2, 3]
df # add new column - dept_id - list - length of list should be equal to number of rows in df

   ID      Name     Score  Passed     Remarks  Dept_ID
0   1  Prashant       3.5    True  No Remarks        1
1   2     Rohit       4.5   False  No Remarks        1
2   3      Sita       5.0    True  No Remarks        2
3   5     Rahul  4.333333   False  No Remarks        3

In [49]:
new_df = pd.merge(df, df2, left_on="Dept_ID", right_on="ID", how="outer")
new_df

   ID_x      Name     Score  Passed     Remarks  Dept_ID  ID_y Department
0     1  Prashant       3.5    True  No Remarks        1     1         HR
1     2     Rohit       4.5   False  No Remarks        1     1         HR
2     3      Sita       5.0    True  No Remarks        2     2    Finance
3     5     Rahul  4.333333   False  No Remarks        3     3         IT

In [52]:
df.dropna(inplace=True) # dropna - remove rows with NaN values - inplace - True - modify original df
df.loc[len(df)] = [6, "Neha", 4.5, False, "No Remarks", None]
df # append - add row to df - ignore_index - True - reset index

   ID      Name     Score  Passed     Remarks Dept_ID
0   1  Prashant       3.5    True  No Remarks       1
1   2     Rohit       4.5   False  No Remarks       1
2   3      Sita       5.0    True  No Remarks       2
3   5     Rahul  4.333333   False  No Remarks       3
4   6      Neha       4.5   False  No Remarks    None

In [53]:
new_df = pd.merge(df, df2, left_on="Dept_ID", right_on="ID", how="inner")
new_df

   ID_x      Name     Score  Passed     Remarks Dept_ID  ID_y Department
0     1  Prashant       3.5    True  No Remarks       1     1         HR
1     2     Rohit       4.5   False  No Remarks       1     1         HR
2     3      Sita       5.0    True  No Remarks       2     2    Finance
3     5     Rahul  4.333333   False  No Remarks       3     3         IT

In [54]:
new_df = pd.merge(df, df2, left_on="Dept_ID", right_on="ID", how="outer")
new_df

   ID_x      Name     Score  Passed     Remarks Dept_ID  ID_y Department
0     1  Prashant       3.5    True  No Remarks       1   1.0         HR
1     2     Rohit       4.5   False  No Remarks       1   1.0         HR
2     3      Sita       5.0    True  No Remarks       2   2.0    Finance
3     5     Rahul  4.333333   False  No Remarks       3   3.0         IT
4     6      Neha       4.5   False  No Remarks    None   NaN        NaN

In [65]:
df2.drop(df2[df2['Department'] == "Finance"].index, inplace=True) # dropna - remove rows with NaN values - inplace - True - modify original df

df2.loc[len(df2)] = [2, "Technology"]
df2.loc[len(df2)] = [3, "Administration"]
df2.loc[len(df2)] = [4, "Finance"]
df2.loc[len(df2)] = [5, "IT"]
df2 # append - add row to df - ignore_index - True - reset index

   ID      Department
0   1              HR
1   2      Technology
2   3  Administration
3   4         Finance
4   5              IT

In [ ]:
new_df = pd.merge(df2, df, left_on="ID", right_on="Dept_ID", how="inner")
new_df

  ID_x      Department ID_y      Name     Score  Passed     Remarks Dept_ID
0    1              HR    1  Prashant       3.5    True  No Remarks       1
1    1              HR    2     Rohit       4.5   False  No Remarks       1
2    2      Technology    3      Sita       5.0    True  No Remarks       2
3    3  Administration    5     Rahul  4.333333   False  No Remarks       3

In [68]:
new_df = pd.merge(df2, df, left_on="ID", right_on="Dept_ID", how="outer")
new_df

  ID_x      Department ID_y      Name     Score Passed     Remarks Dept_ID
0    1              HR    1  Prashant       3.5   True  No Remarks       1
1    1              HR    2     Rohit       4.5  False  No Remarks       1
2    2      Technology    3      Sita       5.0   True  No Remarks       2
3    3  Administration    5     Rahul  4.333333  False  No Remarks       3
4    4         Finance  NaN       NaN       NaN    NaN         NaN     NaN
5    5              IT  NaN       NaN       NaN    NaN         NaN     NaN